#!/usr/bin/env python3
# Subset the Zpix pixel font to only the glyphs the app can show, then base64-inline it into
# miniprogram/styles/zpix.wxss so the font SHIPS IN THE PACKAGE — no CDN, no downloadFile 合法域名,
# the runtime never downloads it, and every user sees identical pixel text.
#
# FALLBACK (by design): the subset's cmap contains ONLY the included chars. Any char NOT in the
# subset is simply absent from the Zpix font, so the renderer falls back PER-CHARACTER to the next
# font in the `font-family` stack (app.wxss: "Zpix", "PingFang SC", -apple-system, ... ). Result:
# a rare/uncommon char renders in the SYSTEM font — never a tofu box (□).
#
# Source font (4.4MB, NOT in git): scripts/fonts/Zpix.ttf  (SolidZORO/zpix-pixel-font)
# Regenerate after adding new copy/UI text:  pip install fonttools && python3 scripts/build-font.py
import glob, re, base64, os, sys, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "scripts/fonts/Zpix.ttf")
OUT = os.path.join(ROOT, "miniprogram/styles/zpix.wxss")
CHARSET = "/tmp/cloudpet-charset.txt"
SUBSET = "/tmp/cloudpet-zpix-subset.ttf"

# 1) every Han char the app actually renders (authored copy + UI text)
chars = set()
for pat in ["web/src/data/copybank/*.json", "web/src/data/*.ts",
            "miniprogram/pages/*/*.wxml", "miniprogram/pages/*/*.ts",
            "miniprogram/*.wxss", "miniprogram/pages/*/*.wxss"]:
    for f in glob.glob(os.path.join(ROOT, pat)):
        try:
            chars |= set(re.findall(r"[一-鿿]", open(f, encoding="utf-8").read()))
        except Exception:
            pass
proj = len(chars)

# 2) + GB2312 level-1 常用字 (~3755) so user-typed pet names are covered ~99%
for b1 in range(0xB0, 0xD8):
    for b2 in range(0xA1, 0xFF):
        try:
            chars.add(bytes([b1, b2]).decode("gb2312"))
        except Exception:
            pass

# 3) + ASCII + common CN/EN punctuation
chars |= set(map(chr, range(0x20, 0x7F)))
chars |= set("　，。、！？：；…—～·「」『』（）【】《》“”‘’％℃→←♥")

open(CHARSET, "w", encoding="utf-8").write("".join(sorted(chars)))

# 4) subset (default: chars outside the set are NOT in the output cmap → system-font fallback)
subprocess.run([sys.executable, "-m", "fontTools.subset", SRC,
                "--text-file=" + CHARSET, "--output-file=" + SUBSET,
                "--no-hinting", "--desubroutinize", "--layout-features='*'"], check=True)

# 5) base64 → @font-face wxss
b64 = base64.b64encode(open(SUBSET, "rb").read()).decode()
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("/* AUTO-GENERATED by scripts/build-font.py — do not hand-edit.\n"
            "   Subsetted Zpix pixel font, base64-inlined so it ships IN the package (no CDN,\n"
            "   no downloadFile 合法域名, runtime never downloads it, identical for every user).\n"
            "   Chars NOT in the subset fall back per-character to the system font via the\n"
            "   font-family stack in app.wxss ('Zpix', 'PingFang SC', ...) — never tofu boxes. */\n")
    f.write('@font-face { font-family: "Zpix"; src: url("data:font/ttf;base64,'
            + b64 + '") format("truetype"); }\n')

print("项目用字 %d + GB2312/标点 → 子集 %d 字符 | ttf %dKB → wxss %dKB"
      % (proj, len(chars), os.path.getsize(SUBSET) // 1024, os.path.getsize(OUT) // 1024))
